language: node_js
after_success:
  - npm run report
node_js:
  - '8'
  - '10'
  - '12'
  - '13'
jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      node_js: '12'
      services:
        - docker
      script: skip
      after_success: echo Skipping coverage.
      deploy:
        provider: script
        script: bash docker-deploy.sh
        on:
          branch: master
